name: recibo_facil
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  cunning_document_scanner: ^1.2.3  
  go_router: ^14.6.3
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  copy_with_extension: ^5.0.4
  google_mlkit_text_recognition: ^0.14.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: any
  pdfrx: ^1.0.88
  file_picker: ^8.1.4
  get_it: ^8.0.2
  diacritic: ^0.1.6
  decimal: ^3.0.2
  fl_chart: ^0.69.2
  shimmer: ^3.0.0
  interactive_viewer_2: ^0.0.10
  pdf_render: ^1.4.12
  lottie: ^3.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  

  mockito: ^5.3.2
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  copy_with_extension_gen: ^5.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
 
 

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/iconos/

fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic    
